default:
  address: "127.0.0.1:25575" # host:port, for example 127.0.0.1:16260
  password: "Descent3$"
  log: "/var/www/html/pal_server/logs/rcon-default.log"
  type: "web" # rcon, telnet, web.
  timeout: "10s"
